export { default as Auth } from './Auth/Auth';
export { default as Admin } from './Admin/Admin';
export { default as Basket } from './Basket/Basket';
export { default as Contacts } from './Contacts/Contacts';
export { default as Delivery } from './Delivery/Delivery';
export { default as News } from './News/News';
export { default as Plant } from './Plant/Plant';
export { default as Shop } from './Shop/Shop';
export { default as Home } from './Home/Home';
